version: "3.8"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - migrate

  migrate:
    build: .
    command: python manage.py migrate
    env_file:
      - .env
